name: hoax-detection-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - torchvision
      - transformers
      - scikit-learn
      - pandas
      - matplotlib
      - seaborn
      - wordcloud
      - tqdm
      - mlflow
      - datasets
      - nltk
      - protobuf<4.0.0
