# conda.yaml
name: rf_hoax_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - mlflow
      - python-dotenv
      - joblib
