version: '3.8'

services:
  inference:
    image: muthiah192/rf-hoax-model:latest
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - ./inference_service/rf_model:/app/rf_model

  exporter:
    build:
      context: ./Monitoring
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./Monitoring/classification_metrics.json:/app/classification_metrics.json

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./Monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=amirahannazihah@gmail.com
      - GF_SMTP_PASSWORD=APP_PASS
      - GF_SMTP_FROM_ADDRESS=amirahannazihah@gmail.com
      - GF_SMTP_SKIP_VERIFY=true

volumes:
  grafana-storage:
