name: hoax-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - ipykernel
  - setuptools
  - wheel
  - pip:
      - torch       
      - transformers
      - pandas
      - scikit-learn
      - mlflow
      - huggingface_hub
      - fastapi
      - uvicorn
      - gunicorn
      - protobuf<4.0.0  # Supaya kompatibel dengan beberapa paket
      - python-dotenv  # Buat load file .env 
      - requests       
