global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hoax_detection_exporter'
    static_configs:
      - targets: ['exporter:8000']

  - job_name: 'inference_metrics'
    static_configs:
      - targets: ['inference:8001']
