# .github/workflows/ci.yaml
name: Train and Deploy RF Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-train-log:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true

      - name: Install MLflow
        run: |
          conda install -y pip
          pip install mlflow

      - name: Run MLflow project (train and log)
        run: |
          mlflow run Model

      - name: Build Docker image
        run: |
          mlflow models build-docker -m mlruns/0/*/artifacts/rf_model -n rf-hoax-model

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag rf-hoax-model ${{ secrets.DOCKERHUB_USERNAME }}/rf-hoax-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rf-hoax-model:latest
