name: MLflow CI

on:
  push:
    paths:
      - '.github/workflows/ci.yaml'
      - 'Model/MLProject'
      - 'Model/conda.yaml'
      - 'Model/train_and_log.py'  # Tambahkan file yang terkait dengan training
      - 'Model/inference.py'  # Jika ada update pada inference
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Menggunakan requirements.txt daripada install manual

      - name: Set up Conda environment
        run: |
          conda env create -f Model/conda.yaml
          conda activate hoax-detection

      - name: Run MLflow Project
        run: |
          mlflow run . --experiment-name hoax-detection --epochs 3 --batch_size 16

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mlflow-artifacts
          path: mlruns  # Upload artifacts dari folder mlruns yang digunakan oleh MLflow
