name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install MLflow
      run: pip install mlflow

    - name: Build Docker Image from MLflow Model
      run: |
        mlflow models build-docker \
          -m $(pwd)/mlflow_model/model \
          -n distilbert-hoax-classifier

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: |
        docker tag fact-hoax-classifier ${{ secrets.DOCKER_USERNAME }}/fact-hoax-classifier:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/fact-hoax-classifier:latest
