name: Model Training and Logging

on:
  push:
    paths:
      - 'Model/train_and_log.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Download processed dataset artifact
      uses: actions/download-artifact@v4
      with:
        name: processed-dataset
        path: data

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Training and Log with MLflow
      run: |
        python Model/train_and_log.py
